/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "uz" | "ru" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  uz: {
    // SEO Meta
    "meta.home.title": "Chorvador.uz - Qishloq xo'jaligi mahsulotlari | Traktor, Urug', O'g'it",
    "meta.home.description": "O'zbekistonda qishloq xo'jaligi texnikasi, urug'lar, o'g'itlar va chorvachilik mahsulotlarining ishonchli yetkazib beruvchisi. 20+ yillik tajriba.",
    "meta.about.title": "Biz haqimizda - Chorvador.uz | 20+ Yillik Tajriba",
    "meta.about.description": "Chorvador.uz 2004-yildan beri O'zbekiston fermerlariga xizmat qiladi. Sifatli mahsulotlar va professional xizmat.",
    "meta.products.title": "Mahsulotlar - Chorvador.uz | Traktor, Urug', O'g'it",
    "meta.products.description": "Qishloq xo'jaligi texnikasi, urug'lar, o'g'itlar, chorvachilik uskunalari. 500+ mahsulot turlari.",
    "meta.services.title": "Xizmatlar - Chorvador.uz | Yetkazib berish, Texnik xizmat",
    "meta.services.description": "Yetkazib berish, texnik xizmat, maslahat, kafolat xizmatlari. Fermerlar uchun to'liq qo'llab-quvvatlash.",
    "meta.contact.title": "Bog'lanish - Chorvador.uz | Aloqa Ma'lumotlari",
    "meta.contact.description": "Chorvador.uz bilan bog'laning. Toshkent, Chilonzor. Tel: +998 90 123 45 67",
    
    // Navigation
    "nav.home": "Bosh sahifa",
    "nav.about": "Biz haqimizda",
    "nav.products": "Mahsulotlar",
    "nav.services": "Xizmatlar",
    "nav.contact": "Aloqa",
    "nav.login": "Kirish",
    "nav.order": "Buyurtma berish",
    "nav.workHours": "Ish vaqti: 09:00 - 18:00",
    
    // Hero
    "hero.slide1.title": "Qishloq xo'jaligining ishonchli hamkori",
    "hero.slide1.subtitle": "Eng sifatli texnika va uskunalar",
    "hero.slide1.description": "20+ yillik tajriba va 1000+ mamnun mijozlar bilan O'zbekiston fermerlariga xizmat qilamiz",
    "hero.slide1.cta": "Mahsulotlarni ko'rish",
    "hero.slide2.title": "Yuqori sifatli urug'lar",
    "hero.slide2.subtitle": "Hosildorlikni oshiring",
    "hero.slide2.description": "Import va mahalliy ishlab chiqarilgan sertifikatlangan urug'lar kolleksiyasi",
    "hero.slide2.cta": "Urug'larni ko'rish",
    "hero.slide3.title": "Chorvachilik mahsulotlari",
    "hero.slide3.subtitle": "Hayvonlaringiz uchun eng yaxshisi",
    "hero.slide3.description": "Veterinariya preparatlari, ozuqa qo'shimchalari va chorvachilik uskunalari",
    "hero.slide3.cta": "Batafsil",
    "hero.slide4.title": "O'g'itlar va himoya vositalari",
    "hero.slide4.subtitle": "Ekinlaringizni himoyalang",
    "hero.slide4.description": "Mineral va organik o'g'itlar, o'simliklarni himoya qilish vositalari",
    "hero.slide4.cta": "Ko'proq bilish",
    "hero.contact": "Bog'lanish",
    
    // Stats
    "stats.customers": "Mamnun mijozlar",
    "stats.products": "Mahsulot turlari",
    "stats.experience": "Yillik tajriba",
    "stats.regions": "Viloyatlarda xizmat",
    
    // Featured Products
    "products.badge": "Mahsulotlar",
    "products.title": "Tanlangan mahsulotlar",
    "products.subtitle": "Eng ko'p sotilayotgan va tavsiya etilgan mahsulotlarimiz bilan tanishing",
    "products.viewAll": "Barcha mahsulotlar",
    "products.popular": "Mashhur",
    "products.new": "Yangi",
    "products.discount": "Chegirma",
    "products.view": "Ko'rish",
    "products.addToCart": "Savatga",
    "products.page.title": "Mahsulotlar",
    "products.page.subtitle": "Qishloq xo'jaligi va chorvachilik uchun zarur bo'lgan barcha mahsulotlar bir joyda",
    "products.search": "Mahsulot qidirish...",
    "products.filters": "Filtrlar",
    "products.found": "ta mahsulot topildi",
    "products.notFound": "Hech narsa topilmadi. Boshqa kalit so'z bilan qidirib ko'ring.",
    "products.categories.all": "Barchasi",
    "products.categories.texnika": "Qishloq xo'jaligi texnikasi",
    "products.categories.uruglar": "Urug'lar",
    "products.categories.ogitlar": "O'g'itlar",
    "products.categories.chorvachilik": "Chorvachilik",
    "products.categories.sugorish": "Sug'orish uskunalari",
    
    // Product Detail
    "product.backToProducts": "Mahsulotlarga qaytish",
    "product.price": "so'm",
    "product.addToCart": "Savatga qo'shish",
    "product.callUs": "Qo'ng'iroq qilish",
    "product.warranty": "Rasmiy kafolat",
    "product.freeDelivery": "Bepul yetkazib berish",
    "product.installment": "Muddatli to'lov imkoniyati",
    "product.specifications": "Texnik xususiyatlar",
    "product.video": "Video ko'rsatma",
    "product.similar": "O'xshash mahsulotlar",
    "products.page.loading": "Yuklanmoqda...",
    
    // Services
    "services.badge": "Xizmatlar",
    "services.title": "Bizning xizmatlarimiz",
    "services.subtitle": "Fermerlar va qishloq xo'jaligi sohasida faoliyat yurituvchilar uchun keng qamrovli xizmatlar",
    "services.viewAll": "Barcha xizmatlar",
    "services.more": "Batafsil",
    "services.page.title": "Xizmatlar",
    "services.page.subtitle": "Fermerlar va qishloq xo'jaligi sohasida faoliyat yurituvchilar uchun keng qamrovli xizmatlar",
    "services.types.all": "Barchasi",
    "services.types.delivery": "Yetkazib berish",
    "services.types.technical": "Texnik xizmat",
    "services.types.consulting": "Maslahat",
    "services.types.warranty": "Kafolat",
    "services.delivery.title": "Yetkazib berish xizmati",
    "services.delivery.desc": "O'zbekiston bo'ylab tez va ishonchli yetkazib berish. Katta buyurtmalar uchun bepul yetkazib berish xizmati.",
    "services.delivery.feature1": "1-3 kun ichida yetkazib berish",
    "services.delivery.feature2": "Katta buyurtmalar uchun bepul",
    "services.delivery.feature3": "Onlayn kuzatish",
    "services.technical.title": "Texnik xizmat ko'rsatish",
    "services.technical.desc": "Qishloq xo'jaligi texnikasi va uskunalariga professional texnik xizmat ko'rsatish va ta'mirlash.",
    "services.technical.feature1": "Tajribali mutaxassislar",
    "services.technical.feature2": "Asl ehtiyot qismlar",
    "services.technical.feature3": "Tezkor xizmat",
    "services.consultation.title": "Maslahat xizmati",
    "services.consultation.desc": "Fermerlar uchun bepul maslahat xizmati. Mahsulot tanlash va qo'llashda yordam.",
    "services.consultation.feature1": "Bepul maslahat",
    "services.consultation.feature2": "Tajribali agronomlar",
    "services.consultation.feature3": "24/7 qo'llab-quvvatlash",
    "services.warranty.title": "Kafolat xizmati",
    "services.warranty.desc": "Barcha mahsulotlarga kafolat. Muammoli mahsulotlarni almashtirish yoki ta'mirlash.",
    "services.warranty.feature1": "12 oylik kafolat",
    "services.warranty.feature2": "Bepul almashtirish",
    "services.warranty.feature3": "Tezkor javob",
    "services.rental.title": "Texnikani ijaraga berish",
    "services.rental.desc": "Qishloq xo'jaligi texnikasini mavsumiy ijaraga berish xizmati.",
    "services.rental.feature1": "Qulay narxlar",
    "services.rental.feature2": "Turli texnika",
    "services.rental.feature3": "Operator bilan",
    "services.analysis.title": "Agrokimyoviy tahlil",
    "services.analysis.desc": "Tuproq va o'simliklar tahlili. Samarali o'g'it va himoya vositalarini tanlashda yordam.",
    "services.analysis.feature1": "Laboratoriya tahlili",
    "services.analysis.feature2": "Tavsiyalar",
    "services.analysis.feature3": "Bepul namuna olish",
    
    // About
    "about.title": "Biz haqimizda",
    "about.subtitle": "Chorvador.uz — O'zbekiston bo'ylab qishloq xo'jaligi va chorvachilik mahsulotlarining ishonchli yetkazib beruvchisi",
    "about.history.badge": "Kompaniya tarixi",
    "about.history.title": "20+ yillik tajriba va ishonch",
    "about.history.p1": "Chorvador.uz 2004-yilda tashkil etilgan bo'lib, bugungi kunda O'zbekistondagi eng yirik qishloq xo'jaligi mahsulotlari yetkazib beruvchilaridan biriga aylandi.",
    "about.history.p2": "Biz fermerlar va chorvachilik bilan shug'ullanuvchilar uchun eng sifatli texnika, urug'lar, o'g'itlar, veterinariya preparatlari va boshqa zarur mahsulotlarni taqdim etamiz.",
    "about.history.p3": "Bizning maqsadimiz — O'zbekiston qishloq xo'jaligini zamonaviy texnologiyalar va sifatli mahsulotlar bilan ta'minlash orqali rivojlantirishga hissa qo'shish.",
    "about.history.years": "Yillik tajriba",
    "about.mission.title": "Bizning missiyamiz",
    "about.mission.desc": "O'zbekiston fermerlarini eng sifatli qishloq xo'jaligi mahsulotlari va zamonaviy texnologiyalar bilan ta'minlash, ularga professional maslahat va xizmatlar ko'rsatish orqali mamlakatimiz qishloq xo'jaligining barqaror rivojlanishiga hissa qo'shish.",
    "about.vision.title": "Bizning ko'zlagan maqsadimiz",
    "about.vision.desc": "O'zbekiston va Markaziy Osiyo mintaqasida qishloq xo'jaligi mahsulotlari sohasida yetakchi kompaniyaga aylanish, innovatsion yechimlar va yuqori sifatli xizmatlar bilan mijozlarimizning ishonchini qozonish.",
    "about.values.badge": "Qadriyatlarimiz",
    "about.values.title": "Bizning qadriyatlarimiz",
    "about.values.quality.title": "Sifat",
    "about.values.quality.desc": "Faqat sertifikatlangan va yuqori sifatli mahsulotlarni taqdim etamiz",
    "about.values.reliability.title": "Ishonchlilik",
    "about.values.reliability.desc": "20+ yillik tajriba va minglab mamnun mijozlar",
    "about.values.professionalism.title": "Professionallik",
    "about.values.professionalism.desc": "Malakali mutaxassislar jamoasi va professional xizmat ko'rsatish",
    
    // Contact
    "contact.title": "Bog'lanish",
    "contact.subtitle": "Savollaringiz bormi? Biz bilan bog'laning va mutaxassislarimiz sizga yordam beradi",
    "contact.form.title": "Xabar yuborish",
    "contact.form.name": "Ismingiz",
    "contact.form.namePlaceholder": "Ismingizni kiriting",
    "contact.form.phone": "Telefon raqam",
    "contact.form.phonePlaceholder": "+998 90 123 45 67",
    "contact.form.message": "Xabar",
    "contact.form.messagePlaceholder": "Xabaringizni yozing...",
    "contact.form.submit": "Xabar yuborish",
    "contact.form.submitting": "Yuborilmoqda...",
    "contact.form.success": "Xabar yuborildi!",
    "contact.form.successDesc": "Tez orada siz bilan bog'lanamiz.",
    "contact.info.title": "Aloqa ma'lumotlari",
    "contact.info.subtitle": "Bizning ofisimizga tashrif buyurishingiz yoki quyidagi ma'lumotlar orqali biz bilan bog'lanishingiz mumkin.",
    "contact.address.title": "Manzil",
    "contact.address.value": "Toshkent sh., Chilonzor tumani,\nBunyodkor ko'chasi, 15-uy",
    "contact.phone.title": "Telefon",
    "contact.email.title": "Email",
    "contact.hours.title": "Ish vaqti",
    "contact.hours.value": "Dushanba - Shanba: 09:00 - 18:00\nYakshanba: Dam olish kuni",
    "viewDetails": "Batafsil ko'rish",
    "learnMore": "Ko'proq o'rganish",

    
    // 404
    "404.title": "404",
    "404.subtitle": "Kechirasiz! Sahifa topilmadi",
    "404.description": "Siz qidirayotgan sahifa mavjud emas yoki ko'chirilgan bo'lishi mumkin.",
    "404.home": "Bosh sahifaga qaytish",
    
    // Partners
    "partners.badge": "Hamkorlar",
    "partners.title": "Hamkor kompaniyalar",
    "partners.subtitle": "Dunyo va mahalliy yetakchi kompaniyalar bilan hamkorlik qilamiz",
    
    // Location
    "location.badge": "Manzil",
    "location.title": "Bizning manzilimiz",
    "location.subtitle": "Bizning ofisimizga tashrif buyuring yoki bog'laning",
    "location.address": "Toshkent shahri, Chilonzor tumani, Bunyodkor ko'chasi, 15-uy",
    "location.phone": "+998 90 123 45 67",
    "location.email": "info@chorvador.uz",
    "location.cta": "Bog'lanish",
    
    // Footer
    "footer.description": "O'zbekiston bo'ylab qishloq xo'jaligi va chorvachilik mahsulotlarining ishonchli yetkazib beruvchisi.",
    "footer.company.title": "Kompaniya",
    "footer.company.about": "Biz haqimizda",
    "footer.company.services": "Xizmatlar",
    "footer.company.products": "Mahsulotlar",
    "footer.company.contact": "Aloqa",
    "footer.products.title": "Mahsulotlar",
    "footer.products.machinery": "Qishloq xo'jaligi texnikasi",
    "footer.products.livestock": "Chorvachilik mahsulotlari",
    "footer.products.fertilizers": "O'g'itlar va kimyoviy moddalar",
    "footer.products.seeds": "Urug'lar",
    "footer.services.title": "Xizmatlar",
    "footer.services.technical": "Texnik xizmat ko'rsatish",
    "footer.services.consulting": "Maslahat xizmatlari",
    "footer.services.delivery": "Yetkazib berish",
    "footer.services.warranty": "Kafolat xizmati",
    "footer.contact.title": "Aloqa",
    "footer.contact.address": "Toshkent sh., Chilonzor tumani, Bunyodkor ko'chasi, 15-uy",
    "footer.copyright": "© 2024 Chorvador.uz. Barcha huquqlar himoyalangan.",
    "footer.privacy": "Maxfiylik siyosati",
    "footer.terms": "Foydalanish shartlari",
  },
  ru: {
    // SEO Meta
    "meta.home.title": "Chorvador.uz - Сельхозпродукция | Трактор, Семена, Удобрения",
    "meta.home.description": "Надёжный поставщик сельскохозяйственной техники, семян, удобрений в Узбекистане. Опыт 20+ лет.",
    "meta.about.title": "О нас - Chorvador.uz | 20+ Лет Опыта",
    "meta.about.description": "Chorvador.uz обслуживает фермеров Узбекистана с 2004 года. Качественная продукция и профессиональный сервис.",
    "meta.products.title": "Продукция - Chorvador.uz | Трактор, Семена, Удобрения",
    "meta.products.description": "Сельхозтехника, семена, удобрения, оборудование для животноводства. 500+ видов продукции.",
    "meta.services.title": "Услуги - Chorvador.uz | Доставка, Техобслуживание",
    "meta.services.description": "Доставка, техобслуживание, консультации, гарантия. Полная поддержка фермеров.",
    "meta.contact.title": "Контакты - Chorvador.uz | Связаться с Нами",
    "meta.contact.description": "Свяжитесь с Chorvador.uz. Ташкент, Чиланзар. Тел: +998 90 123 45 67",
    
    // Navigation
    "nav.home": "Главная",
    "nav.about": "О нас",
    "nav.products": "Продукты",
    "nav.services": "Услуги",
    "nav.contact": "Контакты",
    "nav.login": "Войти",
    "nav.order": "Заказать",
    "nav.workHours": "Рабочее время: 09:00 - 18:00",
    
    // Hero
    "hero.slide1.title": "Надёжный партнёр сельского хозяйства",
    "hero.slide1.subtitle": "Качественная техника и оборудование",
    "hero.slide1.description": "20+ лет опыта и 1000+ довольных клиентов. Служим фермерам Узбекистана",
    "hero.slide1.cta": "Смотреть продукты",
    "hero.slide2.title": "Высококачественные семена",
    "hero.slide2.subtitle": "Повысьте урожайность",
    "hero.slide2.description": "Коллекция сертифицированных импортных и местных семян",
    "hero.slide2.cta": "Смотреть семена",
    "hero.slide3.title": "Продукция для животноводства",
    "hero.slide3.subtitle": "Лучшее для ваших животных",
    "hero.slide3.description": "Ветеринарные препараты, кормовые добавки и оборудование",
    "hero.slide3.cta": "Подробнее",
    "hero.slide4.title": "Удобрения и средства защиты",
    "hero.slide4.subtitle": "Защитите свои посевы",
    "hero.slide4.description": "Минеральные и органические удобрения, средства защиты растений",
    "hero.slide4.cta": "Узнать больше",
    "hero.contact": "Связаться",
    
    // Stats
    "stats.customers": "Довольных клиентов",
    "stats.products": "Видов продукции",
    "stats.experience": "Лет опыта",
    "stats.regions": "Регионов обслуживания",
    
    // Featured Products
    "products.badge": "Продукты",
    "products.title": "Избранные продукты",
    "products.subtitle": "Ознакомьтесь с нашими самыми продаваемыми и рекомендуемыми товарами",
    "products.viewAll": "Все продукты",
    "products.popular": "Популярное",
    "products.new": "Новинка",
    "products.discount": "Скидка",
    "products.view": "Смотреть",
    "products.addToCart": "В корзину",
    "products.page.title": "Продукты",
    "products.page.subtitle": "Вся необходимая продукция для сельского хозяйства и животноводства в одном месте",
    "products.search": "Поиск продукта...",
    "products.filters": "Фильтры",
    "products.found": "продуктов найдено",
    "products.notFound": "Ничего не найдено. Попробуйте другой запрос.",
    "products.categories.all": "Все",
    "products.categories.texnika": "Сельхозтехника",
    "products.categories.uruglar": "Семена",
    "products.categories.ogitlar": "Удобрения",
    "products.categories.chorvachilik": "Животноводство",
    "products.categories.sugorish": "Оросительное оборудование",
    
    // Product Detail
    "product.backToProducts": "Вернуться к продуктам",
    "product.price": "сум",
    "product.addToCart": "В корзину",
    "product.callUs": "Позвонить",
    "product.warranty": "Официальная гарантия",
    "product.freeDelivery": "Бесплатная доставка",
    "product.installment": "Рассрочка",
    "product.specifications": "Технические характеристики",
    "product.video": "Видео инструкция",
    "product.similar": "Похожие товары",
    "products.page.loading": "Загрузка...",
    
    // Services
    "services.badge": "Услуги",
    "services.title": "Наши услуги",
    "services.subtitle": "Комплексные услуги для фермеров и работников сельского хозяйства",
    "services.viewAll": "Все услуги",
    "services.more": "Подробнее",
    "services.page.title": "Услуги",
    "services.page.subtitle": "Комплексные услуги для фермеров и работников сельского хозяйства",
    "services.types.all": "Все",
    "services.types.delivery": "Доставка",
    "services.types.technical": "Техобслуживание",
    "services.types.consulting": "Консультации",
    "services.types.warranty": "Гарантия",
    "services.delivery.title": "Служба доставки",
    "services.delivery.desc": "Быстрая и надёжная доставка по всему Узбекистану. Бесплатная доставка для крупных заказов.",
    "services.delivery.feature1": "Доставка за 1-3 дня",
    "services.delivery.feature2": "Бесплатно для крупных заказов",
    "services.delivery.feature3": "Онлайн отслеживание",
    "services.technical.title": "Техническое обслуживание",
    "services.technical.desc": "Профессиональное техническое обслуживание и ремонт сельхозтехники и оборудования.",
    "services.technical.feature1": "Опытные специалисты",
    "services.technical.feature2": "Оригинальные запчасти",
    "services.technical.feature3": "Быстрый сервис",
    "services.consultation.title": "Консультационная служба",
    "services.consultation.desc": "Бесплатные консультации для фермеров. Помощь в выборе и применении продукции.",
    "services.consultation.feature1": "Бесплатные консультации",
    "services.consultation.feature2": "Опытные агрономы",
    "services.consultation.feature3": "Поддержка 24/7",
    "services.warranty.title": "Гарантийный сервис",
    "services.warranty.desc": "Гарантия на всю продукцию. Замена или ремонт проблемных товаров.",
    "services.warranty.feature1": "Гарантия 12 месяцев",
    "services.warranty.feature2": "Бесплатная замена",
    "services.warranty.feature3": "Быстрый отклик",
    "services.rental.title": "Аренда техники",
    "services.rental.desc": "Сезонная аренда сельскохозяйственной техники.",
    "services.rental.feature1": "Доступные цены",
    "services.rental.feature2": "Разная техника",
    "services.rental.feature3": "С оператором",
    "services.analysis.title": "Агрохимический анализ",
    "services.analysis.desc": "Анализ почвы и растений. Помощь в выборе эффективных удобрений и средств защиты.",
    "services.analysis.feature1": "Лабораторный анализ",
    "services.analysis.feature2": "Рекомендации",
    "services.analysis.feature3": "Бесплатный отбор проб",
    
    // About
    "about.title": "О нас",
    "about.subtitle": "Chorvador.uz — надёжный поставщик сельскохозяйственной и животноводческой продукции по всему Узбекистану",
    "about.history.badge": "История компании",
    "about.history.title": "20+ лет опыта и доверия",
    "about.history.p1": "Chorvador.uz была основана в 2004 году и сегодня является одним из крупнейших поставщиков сельхозпродукции в Узбекистане.",
    "about.history.p2": "Мы предоставляем фермерам и животноводам качественную технику, семена, удобрения, ветпрепараты и другую необходимую продукцию.",
    "about.history.p3": "Наша цель — способствовать развитию сельского хозяйства Узбекистана, обеспечивая современные технологии и качественную продукцию.",
    "about.history.years": "Лет опыта",
    "about.mission.title": "Наша миссия",
    "about.mission.desc": "Обеспечить фермеров Узбекистана качественной сельхозпродукцией и современными технологиями, предоставляя профессиональные консультации и услуги для устойчивого развития сельского хозяйства нашей страны.",
    "about.vision.title": "Наше видение",
    "about.values.quality.title": "Качество",
    "about.values.quality.desc": "Предлагаем только сертифицированную и высококачественную продукцию",
    "about.values.reliability.title": "Надёжность",
    "about.values.reliability.desc": "20+ лет опыта и тысячи довольных клиентов",
    "about.values.professionalism.title": "Профессионализм",
    "about.values.professionalism.desc": "Команда квалифицированных специалистов и профессиональный сервис",
    
    // Contact
    "contact.title": "Контакты",
    "contact.subtitle": "Есть вопросы? Свяжитесь с нами, и наши специалисты вам помогут",
    "contact.form.title": "Отправить сообщение",
    "contact.form.name": "Ваше имя",
    "contact.form.namePlaceholder": "Введите ваше имя",
    "contact.form.phone": "Телефон",
    "contact.form.phonePlaceholder": "+998 90 123 45 67",
    "contact.form.message": "Сообщение",
    "contact.form.messagePlaceholder": "Напишите ваше сообщение...",
    "contact.form.submit": "Отправить сообщение",
    "contact.form.submitting": "Отправка...",
    "contact.form.success": "Сообщение отправлено!",
    "contact.form.successDesc": "Мы свяжемся с вами в ближайшее время.",
    "contact.info.title": "Контактная информация",
    "contact.info.subtitle": "Вы можете посетить наш офис или связаться с нами следующими способами.",
    "contact.address.title": "Адрес",
    "contact.address.value": "г. Ташкент, Чиланзарский район,\nул. Бунёдкор, дом 15",
    "contact.phone.title": "Телефон",
    "contact.email.title": "Email",
    "contact.hours.title": "Рабочее время",
    "contact.hours.value": "Понедельник - Суббота: 09:00 - 18:00\nВоскресенье: Выходной",
    "viewDetails": "Подробнее",
    "learnMore": "Узнать больше",
    
    // 404
    "404.title": "404",
    "404.subtitle": "Извините! Страница не найдена",
    "404.description": "Страница, которую вы ищете, не существует или была перемещена.",
    "404.home": "Вернуться на главную",
    
    // Partners
    "partners.badge": "Партнёры",
    "partners.title": "Компании-партнёры",
    "partners.subtitle": "Сотрудничаем с ведущими мировыми и местными компаниями",
    
    // Location
    "location.badge": "Адрес",
    "location.title": "Наш адрес",
    "location.subtitle": "Посетите наш офис или свяжитесь с нами",
    "location.address": "г. Ташкент, Чиланзарский район, ул. Бунёдкор, дом 15",
    "location.phone": "+998 90 123 45 67",
    "location.email": "info@chorvador.uz",
    "location.cta": "Связаться",
    
    // Footer
  "footer.description": "Надежный поставщик сельскохозяйственной и животноводческой продукции по всему Узбекистану.",
  "footer.company.title": "Компания",
  "footer.company.about": "О нас",
  "footer.company.services": "Услуги",
  "footer.company.products": "Продукция",
  "footer.company.contact": "Контакты",
  "footer.products.title": "Продукция",
  "footer.products.machinery": "Сельскохозяйственная техника",
  "footer.products.livestock": "Животноводческая продукция",
  "footer.products.fertilizers": "Удобрения и химические вещества",
  "footer.products.seeds": "Семена",
  "footer.services.title": "Услуги",
  "footer.services.technical": "Техническое обслуживание",
  "footer.services.consulting": "Консультационные услуги",
  "footer.services.delivery": "Доставка",
  "footer.services.warranty": "Гарантийное обслуживание",
  "footer.contact.title": "Контакты",
  "footer.contact.address": "г. Ташкент, Чиланзарский район, улица Бунёдкор, дом 15",
  "footer.copyright": "© 2024 Chorvador.uz. Все права защищены.",
  "footer.privacy": "Политика конфиденциальности",
  "footer.terms": "Условия использования"
  },
  en: {
    // SEO Meta
    "meta.home.title": "Chorvador.uz - Agricultural Products | Tractor, Seeds, Fertilizers",
    "meta.home.description": "Reliable supplier of agricultural machinery, seeds, fertilizers in Uzbekistan. 20+ years of experience.",
    "meta.about.title": "About Us - Chorvador.uz | 20+ Years Experience",
    "meta.about.description": "Chorvador.uz has been serving Uzbekistan farmers since 2004. Quality products and professional service.",
    "meta.products.title": "Products - Chorvador.uz | Tractor, Seeds, Fertilizers",
    "meta.products.description": "Agricultural machinery, seeds, fertilizers, livestock equipment. 500+ product types.",
    "meta.services.title": "Services - Chorvador.uz | Delivery, Technical Service",
    "meta.services.description": "Delivery, technical service, consultation, warranty services. Full support for farmers.",
    "meta.contact.title": "Contact - Chorvador.uz | Get in Touch",
    "meta.contact.description": "Contact Chorvador.uz. Tashkent, Chilanzar. Tel: +998 90 123 45 67",
    
    // Navigation
    "nav.home": "Home",
    "nav.about": "About Us",
    "nav.products": "Products",
    "nav.services": "Services",
    "nav.contact": "Contact",
    "nav.login": "Login",
    "nav.order": "Order Now",
    "nav.workHours": "Working hours: 09:00 - 18:00",
    
    // Hero
    "hero.slide1.title": "Reliable Partner in Agriculture",
    "hero.slide1.subtitle": "Quality Equipment & Machinery",
    "hero.slide1.description": "20+ years of experience and 1000+ satisfied customers serving farmers in Uzbekistan",
    "hero.slide1.cta": "View Products",
    "hero.slide2.title": "High Quality Seeds",
    "hero.slide2.subtitle": "Increase Your Yield",
    "hero.slide2.description": "Collection of certified imported and locally produced seeds",
    "hero.slide2.cta": "View Seeds",
    "hero.slide3.title": "Livestock Products",
    "hero.slide3.subtitle": "Best for Your Animals",
    "hero.slide3.description": "Veterinary preparations, feed additives and livestock equipment",
    "hero.slide3.cta": "Learn More",
    "hero.slide4.title": "Fertilizers & Protection",
    "hero.slide4.subtitle": "Protect Your Crops",
    "hero.slide4.description": "Mineral and organic fertilizers, plant protection products",
    "hero.slide4.cta": "Learn More",
    "hero.contact": "Contact Us",
    
    // Stats
    "stats.customers": "Happy Customers",
    "stats.products": "Product Types",
    "stats.experience": "Years Experience",
    "stats.regions": "Regions Served",
    
    // Featured Products
    "products.badge": "Products",
    "products.title": "Featured Products",
    "products.subtitle": "Explore our best-selling and recommended products",
    "products.viewAll": "All Products",
    "products.popular": "Popular",
    "products.new": "New",
    "products.discount": "Sale",
    "products.view": "View",
    "products.addToCart": "Add to Cart",
    "products.page.title": "Products",
    "products.page.subtitle": "All necessary products for agriculture and livestock in one place",
    "products.search": "Search products...",
    "products.filters": "Filters",
    "products.found": "products found",
    "products.notFound": "Nothing found. Try a different search term.",
    "products.categories.all": "All",
    "products.categories.texnika": "Agricultural Machinery",
    "products.categories.uruglar": "Seeds",
    "products.categories.ogitlar": "Fertilizers",
    "products.categories.chorvachilik": "Livestock",
    "products.categories.sugorish": "Irrigation Equipment",
    
    // Product Detail
    "product.backToProducts": "Back to Products",
    "product.price": "sum",
    "product.addToCart": "Add to Cart",
    "product.callUs": "Call Us",
    "product.warranty": "Official Warranty",
    "product.freeDelivery": "Free Delivery",
    "product.installment": "Installment Available",
    "product.specifications": "Technical Specifications",
    "product.video": "Video Guide",
    "product.similar": "Similar Products",
    "products.page.loading": "Loading...",
    
    // Services
    "services.badge": "Services",
    "services.title": "Our Services",
    "services.subtitle": "Comprehensive services for farmers and agricultural workers",
    "services.viewAll": "All Services",
    "services.more": "Learn More",
    "services.page.title": "Services",
    "services.page.subtitle": "Comprehensive services for farmers and agricultural workers",
    "services.types.all": "All",
    "services.types.delivery": "Delivery",
    "services.types.technical": "Technical",
    "services.types.consulting": "Consultation",
    "services.types.warranty": "Warranty",
    "services.delivery.title": "Delivery Service",
    "services.delivery.desc": "Fast and reliable delivery across Uzbekistan. Free delivery for large orders.",
    "services.delivery.feature1": "1-3 day delivery",
    "services.delivery.feature2": "Free for large orders",
    "services.delivery.feature3": "Online tracking",
    "services.technical.title": "Technical Service",
    "services.technical.desc": "Professional technical service and repair of agricultural machinery and equipment.",
    "services.technical.feature1": "Experienced specialists",
    "services.technical.feature2": "Original spare parts",
    "services.technical.feature3": "Fast service",
    "services.consultation.title": "Consultation Service",
    "services.consultation.desc": "Free consultation service for farmers. Help in product selection and application.",
    "services.consultation.feature1": "Free consultation",
    "services.consultation.feature2": "Experienced agronomists",
    "services.consultation.feature3": "24/7 support",
    "services.warranty.title": "Warranty Service",
    "services.warranty.desc": "Warranty on all products. Replacement or repair of problematic items.",
    "services.warranty.feature1": "12-month warranty",
    "services.warranty.feature2": "Free replacement",
    "services.warranty.feature3": "Quick response",
    "services.rental.title": "Equipment Rental",
    "services.rental.desc": "Seasonal rental of agricultural machinery.",
    "services.rental.feature1": "Affordable prices",
    "services.rental.feature2": "Various equipment",
    "services.rental.feature3": "With operator",
    "services.analysis.title": "Agrochemical Analysis",
    "services.analysis.desc": "Soil and plant analysis. Help in selecting effective fertilizers and protection products.",
    "services.analysis.feature1": "Laboratory analysis",
    "services.analysis.feature2": "Recommendations",
    "services.analysis.feature3": "Free sampling",
    
    // About
    "about.title": "About Us",
    "about.subtitle": "Chorvador.uz — a reliable supplier of agricultural and livestock products throughout Uzbekistan",
    "about.history.badge": "Company History",
    "about.history.title": "20+ years of experience and trust",
    "about.history.p1": "Chorvador.uz was founded in 2004 and today has become one of the largest agricultural product suppliers in Uzbekistan.",
    "about.history.p2": "We provide farmers and livestock breeders with quality machinery, seeds, fertilizers, veterinary preparations and other necessary products.",
    "about.history.p3": "Our goal is to contribute to the development of Uzbekistan's agriculture by providing modern technologies and quality products.",
    "about.history.years": "Years of Experience",
    "about.mission.title": "Our Mission",
    "about.mission.desc": "To provide Uzbekistan farmers with quality agricultural products and modern technologies, offering professional advice and services for sustainable development of our country's agriculture.",
    "about.vision.title": "Our Vision",
    "about.vision.desc": "To become a leading company in agricultural products in Uzbekistan and Central Asia, earning customer trust through innovative solutions and high-quality services.",
    "about.values.badge": "Our Values",
    "about.values.title": "Our Values",
    "about.values.quality.title": "Quality",
    "about.values.quality.desc": "We offer only certified and high-quality products",
    "about.values.reliability.title": "Reliability",
    "about.values.reliability.desc": "20+ years of experience and thousands of satisfied customers",
    "about.values.professionalism.title": "Professionalism",
    "about.values.professionalism.desc": "Team of qualified specialists and professional service",
    
    // Contact
    "contact.title": "Contact",
    "contact.subtitle": "Have questions? Contact us and our specialists will help you",
    "contact.form.title": "Send Message",
    "contact.form.name": "Your Name",
    "contact.form.namePlaceholder": "Enter your name",
    "contact.form.phone": "Phone Number",
    "contact.form.phonePlaceholder": "+998 90 123 45 67",
    "contact.form.message": "Message",
    "contact.form.messagePlaceholder": "Write your message...",
    "contact.form.submit": "Send Message",
    "contact.form.submitting": "Sending...",
    "contact.form.success": "Message sent!",
    "contact.form.successDesc": "We will contact you soon.",
    "contact.info.title": "Contact Information",
    "contact.info.subtitle": "You can visit our office or contact us through the following information.",
    "contact.address.title": "Address",
    "contact.address.value": "Tashkent, Chilanzar district,\nBunyodkor street, building 15",
    "contact.phone.title": "Phone",
    "contact.email.title": "Email",
    "contact.hours.title": "Working Hours",
    "contact.hours.value": "Monday - Saturday: 09:00 - 18:00\nSunday: Closed",
    "viewDetails": "View Details",
    "learnMore": "Learn More",
    
    // 404
    "404.title": "404",
    "404.subtitle": "Sorry! Page not found",
    "404.description": "The page you are looking for doesn't exist or has been moved.",
    "404.home": "Return to Home",
    
    // Partners
    "partners.badge": "Partners",
    "partners.title": "Partner Companies",
    "partners.subtitle": "We work with leading global and local companies",
    
    // Location
    "location.badge": "Location",
    "location.title": "Our Location",
    "location.subtitle": "Visit our office or get in touch",
    "location.address": "Tashkent, Chilanzar district, Bunyodkor street, building 15",
    "location.phone": "+998 90 123 45 67",
    "location.email": "info@chorvador.uz",
    "location.cta": "Contact Us",
    
    // Footer
  "footer.description": "A reliable supplier of agricultural and livestock products across Uzbekistan.",
  "footer.company.title": "Company",
  "footer.company.about": "About Us",
  "footer.company.services": "Services",
  "footer.company.products": "Products",
  "footer.company.contact": "Contact",
  "footer.products.title": "Products",
  "footer.products.machinery": "Agricultural Machinery",
  "footer.products.livestock": "Livestock Products",
  "footer.products.fertilizers": "Fertilizers and Chemicals",
  "footer.products.seeds": "Seeds",
  "footer.services.title": "Services",
  "footer.services.technical": "Technical Support",
  "footer.services.consulting": "Consulting Services",
  "footer.services.delivery": "Delivery",
  "footer.services.warranty": "Warranty Service",
  "footer.contact.title": "Contact",
  "footer.contact.address": "15 Bunyodkor Street, Chilonzor District, Tashkent, Uzbekistan",
  "footer.copyright": "© 2024 Chorvador.uz. All rights reserved.",
  "footer.privacy": "Privacy Policy",
  "footer.terms": "Terms of Use"
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "uz";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}